import { Project, StackCategory, TechItem } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'laundry-bisnis',
    title: 'Website Laundry Bisnis',
    description: 'A comprehensive laundry management system built with Laravel, featuring order tracking and automated billing.',
    tags: ['Laravel', 'MySQL', 'Bootstrap'],
    category: 'Web',
    image: 'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?q=80&w=2071&auto=format&fit=crop',
    links: {
      github: 'https://github.com/ChristopherAldoNatanael/Website-Laundry-Bisnis',
    },
    features: ['Order Management', 'Customer Database', 'Reporting System'],
    tech: ['Laravel 10', 'Blade Templates', 'MySQL', 'Midtrans Integration']
  },
  {
    id: 'banyuwangi-tourism',
    title: 'Banyuwangi Website',
    description: 'Tourism portal for Banyuwangi highlighting local attractions, culture, and events with a modern interface.',
    tags: ['React', 'Tailwind', 'Motion'],
    category: 'Web',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    links: {
      github: 'https://github.com/ChristopherAldoNatanael/Banyuwangi-Website',
    },
    features: ['Interactive Map', 'Event Calendar', 'Dynamic Routing'],
    tech: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion']
  },
  {
    id: 'online-shop',
    title: 'Laravel TokoOnline',
    description: 'Full-featured e-commerce platform with cart functionality, secure checkout, and admin dashboard.',
    tags: ['Laravel', 'PHP', 'E-commerce'],
    category: 'Web',
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=2070&auto=format&fit=crop',
    links: {
      github: 'https://github.com/ChristopherAldoNatanael/Laravel-TokoOnline',
    },
    features: ['Product Management', 'Cart System', 'Admin Panel'],
    tech: ['Laravel', 'Spatie Permissions', 'MySQL']
  },
  {
    id: 'game-2d',
    title: 'Project Game 2D',
    description: 'A stylized 2D platformer focusing on smooth mechanics and level design fundamentals.',
    tags: ['Unity', 'C#', 'Game Dev'],
    category: 'Game',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop',
    links: {
      github: 'https://github.com/ChristopherAldoNatanael/ProjectGame2D',
    },
    features: ['Custom Physics', 'Sprite Animations', 'Level Logic'],
    tech: ['Unity', 'C#', 'Aseprite']
  }
];

export const TECH_STACK: TechItem[] = [
  { name: 'React', category: 'Frontend Engineering' },
  { name: 'Next.js', category: 'Frontend Engineering' },
  { name: 'TypeScript', category: 'Frontend Engineering' },
  { name: 'Tailwind CSS', category: 'Frontend Engineering' },
  { name: 'Flutter', category: 'Mobile Development' },
  { name: 'React Native', category: 'Mobile Development' },
  { name: 'Node.js', category: 'Backend Systems' },
  { name: 'Express', category: 'Backend Systems' },
  { name: 'Laravel', category: 'Backend Systems' },
  { name: 'REST APIs', category: 'Backend Systems' },
  { name: 'MySQL', category: 'Database Architecture' },
  { name: 'PostgreSQL', category: 'Database Architecture' },
  { name: 'Firebase', category: 'Database Architecture' },
  { name: 'Docker', category: 'DevOps & Deployment' },
  { name: 'Git', category: 'DevOps & Deployment' },
  { name: 'CI/CD', category: 'DevOps & Deployment' },
  { name: 'Figma', category: 'Tooling & Workflow' },
  { name: 'VS Code', category: 'Tooling & Workflow' },
  { name: 'Unity', category: 'Game Development' },
  { name: 'Godot', category: 'Game Development' },
];

export const STACK_CATEGORIES: StackCategory[] = [
  {
    id: 'Frontend Engineering',
    title: 'Frontend Engineering',
    tagline: 'Crafting performant, accessible interfaces',
    description: 'I architect frontend systems with a focus on component reusability, state management efficiency, and user experience depth. Every interface I build prioritizes accessibility standards, fluid interactions, and sustainable codebases that teams can maintain for years.',
    philosophy: [
      'Component architecture over page-level thinking',
      'Accessibility as a first-class requirement',
      'Performance budgets as constraints, not suggestions',
      'Progressive enhancement as philosophy',
    ],
    technologies: [
      { name: 'React', level: 'primary', purpose: 'Primary UI framework for complex applications' },
      { name: 'Next.js', level: 'primary', purpose: 'Production-grade SSR/SSG with optimized routing' },
      { name: 'TypeScript', level: 'primary', purpose: 'Type safety across entire codebase' },
      { name: 'Tailwind CSS', level: 'primary', purpose: 'Utility-first styling with design system consistency' },
      { name: 'Framer Motion', level: 'secondary', purpose: 'Declarative animations and micro-interactions' },
      { name: 'React Query', level: 'secondary', purpose: 'Server state management and caching' },
    ],
    workflow: 'Design → Prototype → Component Architecture → State Management → Accessibility Audit → Performance Profiling → Production',
    highlights: ['SSG/SSR optimized', 'Core Web Vitals focused', 'Accessible by default'],
    labels: ['Production Ready', 'Performance Focused', 'Clean Code Philosophy'],
  },
  {
    id: 'Mobile Development',
    title: 'Mobile Development',
    tagline: 'Native-feeling experiences across platforms',
    description: 'Building mobile applications requires understanding platform constraints, user interaction patterns, and performance boundaries. I develop cross-platform solutions that feel native, with careful attention to gesture navigation, offline capabilities, and battery-conscious implementations.',
    philosophy: [
      'Native performance as the baseline',
      'Offline-first data synchronization',
      'Gesture-first interaction design',
      'Platform-specific UX patterns matter',
    ],
    technologies: [
      { name: 'Flutter', level: 'primary', purpose: 'Cross-platform UI with native performance' },
      { name: 'React Native', level: 'primary', purpose: 'React-based mobile development' },
      { name: 'Dart', level: 'primary', purpose: 'Flutter\'s language for structured UI' },
      { name: 'Swift', level: 'secondary', purpose: 'iOS-specific native implementation' },
      { name: 'Kotlin', level: 'secondary', purpose: 'Android-specific native implementation' },
      { name: 'Firebase', level: 'secondary', purpose: 'Backend-as-a-service for mobile' },
    ],
    workflow: 'Requirements → Platform Analysis → Architecture → Feature Development → Device Testing → Performance Optimization → Store Deployment',
    highlights: ['Cross-platform optimized', 'Native feel achieved', 'App store ready'],
    labels: ['Scalable Architecture', 'Maintainable Systems', 'Developer Experience'],
  },
  {
    id: 'Backend Systems',
    title: 'Backend Systems',
    tagline: 'Scalable APIs and server architecture',
    description: 'Backend development is about designing systems that handle business logic efficiently while maintaining data integrity. I build RESTful APIs and server architectures with clear separation of concerns, proper error handling, and documentation that makes future maintenance straightforward.',
    philosophy: [
      'API contracts as promises',
      'Error handling as user experience',
      'Database queries as optimization opportunities',
      'Security as architecture, not afterthought',
    ],
    technologies: [
      { name: 'Node.js', level: 'primary', purpose: 'Event-driven server runtime' },
      { name: 'Express', level: 'primary', purpose: 'Minimalist API framework' },
      { name: 'Laravel', level: 'primary', purpose: 'PHP framework with elegant syntax' },
      { name: 'REST', level: 'primary', purpose: 'API design principles' },
      { name: 'GraphQL', level: 'secondary', purpose: 'Flexible query language' },
      { name: 'WebSocket', level: 'secondary', purpose: 'Real-time communication' },
    ],
    workflow: 'Requirements → Schema Design → API Architecture → Business Logic → Security Hardening → Load Testing → Monitoring Setup',
    highlights: ['RESTful design', 'JWT authentication', 'Rate limiting implemented'],
    labels: ['Production Ready', 'Scalable Architecture', 'Clean Code Philosophy'],
  },
  {
    id: 'Database Architecture',
    title: 'Database Architecture',
    tagline: 'Data modeling for performance and scale',
    description: 'Database design shapes application capabilities for years. I approach data modeling with normalization strategies, query optimization awareness, and future scalability in mind. Whether SQL or NoSQL, the choice depends on access patterns, not trends.',
    philosophy: [
      'Schema as living documentation',
      'Query cost awareness as habit',
      'Data integrity over convenience',
      'Migration strategies prevent downtime',
    ],
    technologies: [
      { name: 'MySQL', level: 'primary', purpose: 'Reliable transactional database' },
      { name: 'PostgreSQL', level: 'primary', purpose: 'Advanced features and JSON support' },
      { name: 'Firebase', level: 'primary', purpose: 'Real-time database with offline sync' },
      { name: 'Redis', level: 'secondary', purpose: 'Caching and session storage' },
      { name: 'MongoDB', level: 'secondary', purpose: 'Document-oriented flexibility' },
      { name: 'Prisma', level: 'secondary', purpose: 'Type-safe ORM' },
    ],
    workflow: 'Requirements → Entity Relationships → Schema Design → Index Strategy → Query Profiling → Migration Planning → Backup Automation',
    highlights: ['Normalized schema', 'Indexed for performance', 'Migrations versioned'],
    labels: ['Maintainable Systems', 'Performance Focused', 'Developer Experience'],
  },
  {
    id: 'DevOps & Deployment',
    title: 'DevOps & Deployment',
    tagline: 'Automation-driven deployment pipelines',
    description: 'Modern deployment is about reliability, reproducibility, and speed. I implement CI/CD pipelines that catch issues before production, containerize applications for consistency across environments, and design infrastructure that scales with demand while minimizing operational overhead.',
    philosophy: [
      'Infrastructure as code',
      'Reproducible environments eliminate "works on my machine"',
      'Automate everything that can be automated',
      'Monitoring is not optional, it\'s foundational',
    ],
    technologies: [
      { name: 'Docker', level: 'primary', purpose: 'Containerization for consistent environments' },
      { name: 'Git', level: 'primary', purpose: 'Version control and branching strategies' },
      { name: 'GitHub Actions', level: 'primary', purpose: 'CI/CD automation' },
      { name: 'Nginx', level: 'secondary', purpose: 'Reverse proxy and load balancing' },
      { name: 'Vercel', level: 'secondary', purpose: 'Frontend deployment platform' },
      { name: 'PM2', level: 'secondary', purpose: 'Node.js process management' },
    ],
    workflow: 'Code → Lint → Test → Build → Containerize → Deploy → Monitor → Iterate',
    highlights: ['Containerized', 'CI/CD automated', 'Zero-downtime deployments'],
    labels: ['Production Ready', 'Scalable Architecture', 'Clean Code Philosophy'],
  },
  {
    id: 'Tooling & Workflow',
    title: 'Tooling & Workflow',
    tagline: 'Developer experience as productivity multiplier',
    description: 'The tools we use shape how we think about problems. I\'ve refined my development environment to minimize friction between thought and implementation. From editor configuration to debugging tools, every piece serves the goal of shipping quality software faster.',
    philosophy: [
      'Keyboard shortcuts are productivity investments',
      'Editor configuration should be version controlled',
      'Debugging tools should reveal, not hide',
      'Documentation is a first-class artifact',
    ],
    technologies: [
      { name: 'VS Code', level: 'primary', purpose: 'Primary code editor with extensive extensions' },
      { name: 'Figma', level: 'primary', purpose: 'Design collaboration and prototyping' },
      { name: 'GitHub', level: 'primary', purpose: 'Version control and collaboration' },
      { name: 'Postman', level: 'secondary', purpose: 'API testing and documentation' },
      { name: 'Chrome DevTools', level: 'secondary', purpose: 'Frontend debugging and profiling' },
      { name: 'iTerm2', level: 'secondary', purpose: 'Terminal with advanced features' },
    ],
    workflow: 'Task → Branch → Develop → Review → Test → Merge → Deploy → Monitor',
    highlights: ['Dotfiles versioned', 'Extensions documented', 'Shortcuts mastered'],
    labels: ['Developer Experience', 'Performance Focused', 'Clean Code Philosophy'],
  },
  {
    id: 'Game Development',
    title: 'Game Development',
    tagline: 'Interactive experiences through code and creativity',
    description: 'Game development combines technical skill with creative problem-solving. I build games with focus on smooth mechanics, efficient physics, and engaging gameplay loops. Every project teaches something about performance optimization, asset management, and user engagement.',
    philosophy: [
      'Frame rate consistency over visual complexity',
      'Game feel emerges from response feedback',
      'Level design teaches through discovery',
      'Player agency is sacred',
    ],
    technologies: [
      { name: 'Unity', level: 'primary', purpose: 'Cross-platform game engine' },
      { name: 'C#', level: 'primary', purpose: 'Unity\'s scripting language' },
      { name: 'Godot', level: 'secondary', purpose: 'Open source engine with GDScript' },
      { name: 'Aseprite', level: 'secondary', purpose: 'Pixel art creation' },
      { name: 'Blender', level: 'secondary', purpose: '3D asset creation' },
      { name: 'FMOD', level: 'familiar', purpose: 'Audio middleware' },
    ],
    workflow: 'Concept → Mechanics Design → Prototype → Art Integration → Polish → Performance → Release',
    highlights: ['Custom physics', 'Optimized rendering', 'Platform tested'],
    labels: ['Production Ready', 'Performance Focused', 'Clean Code Philosophy'],
  },
];